### ISSUE TITLE
Typo on Table 2-1: CIDR?

### ISSUE THREAD

**Issue by n1zea144** [awoodbeck/gnp#1]
I've recently started to read GNP and I'm enjoying it.  I'm wondering if there is a typo in the table 2-1 about CIDR.  Specifically, for the row where CIDR network prefix length is 16.  Shouldn't the available networks be 65536 for a 16 bit network mask and not 256?  I looked at this row because the example was 192.168.156.97/16.

Thanks in advance for any clarifications.

**Comment by awoodbeck** [comment]
Thank you for bringing this to my attention. I appreciate the feedback. I realize that the table heading and accompanying text isn't as clear as it should be.

You are correct. What I meant to convey is the number of Class C or 24-bit networks _within_ each netblock. In other words, there are 256 24-bit networks within each 16-bit netblock. It may not be a particularly useful number, but I meant it to give you a sense of how big each netblock is in relation to a 24-bit network, which is probably the network size you're most likely to encounter especially for a home LAN.

**Comment by n1zea144** [comment]
Ah, that makes sense.  Thanks for the fast reply....just wanted to make sure I wasn't misunderstanding something.
