### ISSUE TITLE
Guide to compiling the examples?

### ISSUE THREAD

**Issue by gmporter** [awoodbeck/gnp#3]
Greetings,

I just started working through this book, and it looks great. I know that the book assumes a working knowledge of Golang, but it might be helpful to have a page or two (or part of the README.md file) explaining how to build/run the examples.

I ask because I teach a class using Go, and we use the original Go book, which is a pre-module book, and so between that book and this one, there isn't any info on how to run the tests.

**Comment by awoodbeck** [comment]
Thank you for your feedback, Dr. Porter. I agree that it would be beneficial to have instruction on setting up your environment, cloning this repo, and running the tests. I'll carve out some time this weekend to work on a step-by-step guide in the README.md.

**Comment by noah-de** [comment]
Greetings @gmporter !
I believe that my last commit (https://github.com/noah-de/gnp/commit/4f9d2d267155f54a84748580e8f81a5e6cec88d0) addresses this issue of running the examples. Do you have further suggestions for README content?

**Comment by gmporter** [comment]
Looks good!  Thanks!

**Comment by awoodbeck** [comment]
I also added an example of how to build and run the code within a Docker container.
